learning_users/basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name = 'register'),
    path('user_login/', views.user_login, name = 'user_login')
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name = 'index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name = 'logout')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete = models.CASCADE)
    portfolio_site = models.URLField(blank = True)
    profile_pic = models.ImageField(upload_to = 'basic_app/profile_pics', blank = True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):

    password = forms.CharField(widget = forms.PasswordInput())

    class Meta():

        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.

def index(request):
    return render(request,'basic_app/index.html')

def register(request):

    registered = False

    if request.method == 'POST':

        user_form = UserForm(data = request.POST)
        profile_form = UserProfileInfoForm(data = request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit = False)
            profile.user = user
            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()
            registered = True

        else:
            print(user_form.errors,profile_form.errors)
    else:

        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    
    return render(request, 'basic_app/register.html', 
                            context = {'registered' : registered,
                                        'user_form' : user_form,
                                        'profile_form' : profile_form})

def user_login(request):

    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)

        if user:
            if user.is_active:
                print('logging in...')
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse('Your account is not active.')
        else:
            print('Someone tried to logon with wrong credentials.')
            print('Username : {} and Password : {}'.format(username, password))
            return HttpResponse("Invalid login details supplied.")
        
    else:
        return render(request, 'basic_app/login.html', {})

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset = "utf-8">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
                    rel="stylesheet" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    </head>
    <body>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="navbar-nav">
              <a class="navbar-brand" href="{% url 'index' %}">DJANGO</a>
              <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
              <a class="nav-item nav-link" href="{% url 'basic_app:register' %}">Register</a>
              {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
              {%endif %}
            </div>
          </nav>

        <div class = "container">
            {% block body_block %}
            <!-- Body code for other pages -->
            {% endblock %}
        </div>

    </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
    <div class = "jumbotron">
        <h1>Django level 5!!</h1>
    </div>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends "basic_app/base.html"%}
{% block body_block %}
    <div class="jumbotron">
        <h1>Please Login here!!</h1>
        <form action="{% url 'basic_app:user_login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username</label>
            <input type="text" name="username" textholder="Enter Username">
            <label for="password">Password</label>
            <input type="password" name="password">
            <input type="submit" name="submit" class="btn btn-primary" value="Login">
        </form>
    </div>
{% endblock %}

learning_users/templates/basic_app/register.html
{% extends "basic_app/base.html" %}

{% block body_block %}

<div class = "jumbotron">
    {% if registered %}
        <h1>Thanks for registering!!</h1>
    {% else %}
        <h1>Register here!!</h1>
        <form enctype = "multipart/form-data" method = "POST">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" class="btn btn-primary" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}